presubmits:
  ucpr/test-tekton-ci:
    - name: unit-tests
      always_run: false
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]

