tide:
  merge_method:
    ucpr/test-tekton-ci: squash

  target_url: https://prow.k8s.io/tide.html

  queries:
  - repos:
    - ucpr/test-tekton-ci
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase

presubmits:
  ucpr/test-tekton-ci:
  - name: unit-test
    trigger: "(?m)^/unit-test"
    rerun_command: "/unit-test"
    always_run: false
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: 
          - "/bin/printenv"

  - name: go-test
    agent: tekton-pipeline # Use the Prow Tekton controller!
    trigger: "(?m)^/go-test,?(\\s+|$)"
    rerun_command: "/go-test"
    always_run: true
    skip_report: false
    pipeline_run_spec: # Template for creation of the `PipelineRun`
      trigger: # Required by versions 0.2.0 - v0.3.1 of Tekton Pipelines
        type: manual
      pipelineRef:
        name: golang-test # Use the Tekton Pipeline called `special-pipeline`
      resources:
      - name: git
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
