tide:
  merge_method:
    ucpr/test-tekton-ci: squash

  target_url: https://prow.k8s.io/tide.html

  queries:
  - repos:
    - ucpr/test-tekton-ci
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase

presubmits:
  ucpr/test-tekton-ci:
  - name: unit-test
    trigger: "(?m)^/test"
    rerun_command: "/test"
    always_run: false
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: 
          - "/bin/printenv"

  - name: go-test
    trigger: "(?m)^/test"
    rerun_command: "/test"
    always_run: false
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: golang
        command: 
          - go
        args:
          - test
          - ./...
