plugins:
  ucpr/test-tekton-ci:
  - size
  - cat
  - golint
  - mergecommitblocker
  - lgtm
  - wip
  - hold
  - approve
  - assign
  - trigger
    #  - dog
    #  - shrug
    #  - pony

triggers:
  - repo:
    - ucpr/test-tekton-ci
