apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: go-test
spec:
  inputs:
    resources:
      - name: gitspace
        type: git
    steps:
      - name: go-test
        images: golang
        command: ["go"]
        args: ["test", "./..."]
